import sys
import os

def add_strings(filepath, strings_dict):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    to_insert = ""
    for k, v in strings_dict.items():
        if f'name="{k}"' not in content:
            to_insert += f'    <string name="{k}">{v}</string>\n'
            
    if to_insert:
        content = content.replace("</resources>", to_insert + "</resources>")
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

strings_en = {
    "empty_created_title": "No created files yet",
    "empty_created_desc": "Files generated by the app will appear here.",
    "empty_opened_title": "No opened files yet",
    "empty_opened_desc": "PDFs you open will appear here.",
    "error_cannot_open_pdf": "Cannot open PDF"
}

strings_ar = {
    "empty_created_title": "لا توجد ملفات منشأة بعد",
    "empty_created_desc": "ستظهر الملفات التي تم إنشاؤها بواسطة التطبيق هنا.",
    "empty_opened_title": "لا توجد ملفات مفتوحة بعد",
    "empty_opened_desc": "ستظهر ملفات PDF التي تفتحها هنا.",
    "error_cannot_open_pdf": "تعذر فتح ملف PDF"
}

strings_es = {
    "empty_created_title": "No hay archivos creados",
    "empty_created_desc": "Los archivos generados por la aplicación aparecerán aquí.",
    "empty_opened_title": "No hay archivos abiertos",
    "empty_opened_desc": "Los PDF que abra aparecerán aquí.",
    "error_cannot_open_pdf": "No se puede abrir el PDF"
}

add_strings('app/src/main/res/values/strings.xml', strings_en)
add_strings('app/src/main/res/values-ar/strings.xml', strings_ar)
add_strings('app/src/main/res/values-es/strings.xml', strings_es)

print("Strings added")
